### PR TITLE
Fix uninitialized global variable

### PR DESCRIPTION
**Pull request by dkloper**
res_init() is called from different places in sockets library. It depends on global _res variable containing a state.

The problem is that if __BIND_RES_TEXT macro is not defined, _res is not initialized. Depending on compiler and build optimization this can fill the variable with garbage that is later used by res_init().

Fix is trivial - explicitly initialize _res.

### CODE REVIEW

**Review by jpshivakavi — APPROVED** [review]

**Comment by jpshivakavi** [comment]
@bcran Could you merge this PR.

**Comment by bcran** [comment]
Sorry for the delay in reviewing this.
This change has a couple of style issues: there shouldn't be a space after the '#', and there's trailing whitespace after '# endif".

**Comment by bcran** [comment]
Also, could you add a signed-off-by line please?

**Comment by jpshivakavi** [comment]
Patch merged using the BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4506

**Comment by jpshivakavi** [comment]
Hence closing this PR

**Pull request closed without merging**
