### PR TITLE
AppPkg: Fix various typos

### PR DESCRIPTION
**Pull request by Coeur**
# Meta
This is an experimental pull request, as discussed many times on the edk2 mailing-list.
It is:
- an easy pull request
- a non-urgent pull request

It fits the experiment of using a GitHub pull request over a mailing-list patch.

Once reviewed and approved, the maintainer of this repo (edk2-libc) has multiple possibilities to handle it:
- either use command line to rebase/merge/etc. this pull request (`git pull https://github.com/coeur/edk2-libc.git Typo-AppPkg`)
- either use the GitHub interface and choose to rebase (or merge or squash): Screen Shot 2019-06-27 at 12 24 32 PM

---
# Pull Request
This is actually a cherry pick of a larger change updated since 2018 at https://github.com/Coeur/edk2/commit/1ee272df2d093236de8a3da14e2c3960a7e8d3eb.

### CODE REVIEW

**Comment by jpshivakavi** [comment]
Recommend you to send a patch review request by rebasing to latest edk2-libc code base. The patch request needs to be sent to [devel@edk2.groups.io](mailto:devel@edk2.groups.io)
You may follow the code contribution instructions provided in https://github.com/tianocore/edk2/blob/master/ReadMe.rst

**Comment by Coeur** [comment]
Not interested in doing patch files anymore. I only do PR.

**Comment by bcran** [comment]
Would you mind if I re-open this and submit the patch to the mailing list myself?
I'd _really_ like the project to stop throwing good contributions away because we're still using outdated practices like requiring people email patches to the mailing list.

**Comment by Coeur** [comment]
Sure. go ahead

**Comment by jpshivakavi** [comment]
@Coeur Could you please add the signed off by tag in the comments section in this format

Signed-off-by: <your email address>

Post this I will be able to submit email patch to [devel@edk2.groups.io](mailto:devel@edk2.groups.io)

**Comment by jpshivakavi** [comment]
@Coeur 
Could you please add the signed off by tag in the comments section in this format
Signed-off-by: Name <email address>

**Comment by Coeur** [comment]
There are no intellectual property at doing spelling corrections.
Feel free to re-appropriate those fixes.
But edk2 process is too archaic for younger generations: I did a PR to encourage PR review and PR merge, not email patches.

**Pull request closed without merging**
